esphome:
  name: esphome-web-af4cb4

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  power_save_mode: LIGHT
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-Af4Cb4"
    password: "JetLOoi94HUv"

captive_portal:

sensor:
  - platform: dht
    model: DHT11
    pin: 22
    temperature:
      name: "esphome-web-af4cb4 Temperature"
      accuracy_decimals: 1
      filters:
        - median:
            window_size: 10
            send_every: 1
            # send_first_at: 5
        - offset: -2.0
    humidity:
      name: "esphome-web-af4cb4 Humidity"
      accuracy_decimals: 2
    update_interval: 2min