substitutions:
  device_id: esphome-web-5c1aad
  sleep_prefix: web5c1aad
  device_name: "esphome-web-5c1aad"
  platform: esp32
  board: esp32dev
  wifi_ssid: !secret wifi_ssid
  wifi_passwd: !secret wifi_password
  ap_wifi_pwd: !secret ap_wifi_pwd
  awake_duration: 10s    # set how long to stay awake - NOT less then 10sec
  update_interval: 5s    # updates sensor data and sends to HA. Needs to be less than awake time
  sleep_duration: 2min   # set how long to sleep in minutes


<<: !include common/esphome.yaml
<<: !include common/esp32.yaml
<<: !include common/common.yaml

i2c:
  - id: bus_a
    sda: 25
    scl: 21
    scan: true

sensor:
  - platform: bh1750
    name: "${device_name} Illuminance"
    i2c_id: bus_a
    address: 0x23
    update_interval: ${update_interval}
    device_class: illuminance
    unit_of_measurement: lx
    icon: "mdi:light"
    accuracy_decimals: 0
  - !include common/sensor/uptime.yaml
  - !include common/sensor/wifi.yaml

binary_sensor:
  - !include common/binary_sensor/prevent_deep_sleep.yaml

text_sensor:
  - !include common/text_sensor/version.yaml
  - !include common/text_sensor/wifi.yaml

script:
  - !include common/script/deep_sleep.yaml

